name: Tests

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches_ignore: []

jobs:
  Dryrun_Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://snakemake/snakemake:v5.24.2
      - name: Dry-run pipeline
        run: |
          docker run -v $PWD:/opt2 snakemake/snakemake:v5.24.2 \
          python /opt2/rna-seek run --input \
          /opt2/.tests/KO_S3.R1.fastq.gz /opt2/.tests/KO_S3.R2.fastq.gz \
          /opt2/.tests/KO_S4.R1.fastq.gz /opt2/.tests/KO_S4.R2.fastq.gz \
          /opt2/.tests/WT_S1.R1.fastq.gz /opt2/.tests/WT_S1.R2.fastq.gz --output /opt2/output --genome hg38_30 --mode local --dry-run
      - name: Lint workflow
        continue-on-error: true
        run: |
          docker run -v $PWD:/opt2 snakemake/snakemake:v5.24.2 snakemake --lint -s /opt2/output/workflow/Snakefile -d /opt2/output || \
          echo 'There may have been a few warnings or errors. Please read through the log to determine if its harmless.'
