name: Tests

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches_ignore: []

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Lint workflow
      continue-on-error: true
      uses: snakemake/snakemake-github-action@v1.5.3
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "--lint -s workflow/Snakefile --configfile=.tests/run.json || echo 'There may have been a few warnings or errors. Please read through the log to determine if its harmless.'"

  Dry-run:
    runs-on: ubuntu-latest
    needs: Linting
    steps:
    - uses: actions/checkout@v2
    - uses: docker://snakemake/snakemake:v5.24.2
    - name: Dry-run workflow
    - run: docker run -v $PWD:/opt2 snakemake/snakemake:v5.24.2 python /opt2/rna-seek run --input /opt2/.tests/KO_S3.R1.fastq.gz /opt2/.tests/KO_S3.R2.fastq.gz /opt2/.tests/KO_S4.R1.fastq.gz /opt2/.tests/KO_S4.R2.fastq.gz /opt2/.tests/WT_S1.R1.fastq.gz /opt2/.tests/WT_S1.R2.fastq.gz /opt2/.tests/WT_S2.R1.fastq.gz /opt2/.tests/WT_S2.R2.fastq.gz --output /opt2/output --genome hg38_30 --mode local --dry-run
