name: Tests

on:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  Dryrun_Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://snakemake/snakemake:v5.24.2
      - name: Dry-run pipeline
        run: |
          docker run -v $PWD:/opt2 -w /opt2 snakemake/snakemake:v5.24.2 \
            python ./src/renee/__main__.py run \
              --input .tests/KO_S3.R1.fastq.gz .tests/KO_S3.R2.fastq.gz .tests/KO_S4.R1.fastq.gz .tests/KO_S4.R2.fastq.gz .tests/WT_S1.R1.fastq.gz .tests/WT_S1.R2.fastq.gz .tests/WT_S2.R1.fastq.gz .tests/WT_S2.R2.fastq.gz \
              --output output \
              --genome config/genomes/biowulf/hg38_30.json \
              --shared-resources .tests/shared_resources/ \
              --mode local \
              --dry-run
      - name: Lint workflow
        continue-on-error: true
        run: |
          docker run -v $PWD:/opt2 snakemake/snakemake:v5.24.2 snakemake --lint -s /opt2/output/workflow/Snakefile -d /opt2/output || \
          echo 'There may have been a few warnings or errors. Please read through the log to determine if its harmless.'

  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: pip
        run: |
          python -m pip install --upgrade pip setuptools pytest
      - name: check CLI basics
        run: |
          ./bin/renee --help
          ./bin/renee --version
      - name: Test
        run: |
          python -m pytest

  build-status: # https://github.com/orgs/community/discussions/4324#discussioncomment-3477871
    runs-on: ubuntu-latest
    needs: [Dryrun_Lint, Test]
    if: always()
    steps:
      - name: Successful build
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failing build
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
