name: Sync Fork

on:
  schedule:
    - cron: "39 11 * * *" # once every day
  workflow_dispatch: # on button click
  push:
    paths:
      - .github/workflows/sync-fork.yml

permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }}
  UPSTREAM_OWNER: CCBR

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        FORK_OWNER: [NCIPangea]
    steps:
      - name: sync fork
        # only run this action from the forked repo
        if: ${{ github.repository_owner == matrix.FORK_OWNER }}
        run: |
          # required for actions scheduled via cron, as github.event.repository.name won't work
          REPO=$(basename ${{ github.repository }})
          # sync the fork from upstream
          gh repo sync ${{ github.repository }} --source $UPSTREAM_OWNER/$REPO --force
